# 기본 통계함수

In [6]:
import numpy as np

#1. 3*3으로 된 2차원 배열 생성
ar = np.arange(1,10)
ar = ar.reshape(3,3)
print(ar)

#2. 모든 데이터를 더한 연산
print("단순 전체 합계:", np.sum(ar))

#3. ★행 단위 열단위 연산
print("열 단위 합계:", np.sum(ar, axis=0))
print("행 단위 합계:", np.sum(ar, axis=1))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
단순 전체 합계: 45
열 단위 합계: [12 15 18]
행 단위 합계: [ 6 15 24]


# 배열 통계

In [10]:
ar = np.array([100,200,300,400])
br = np.array([101,201,301,401])
cond = np.array([True, True, False, False])

#cond의 값이 True이면 ar에서 false이면 br에서 추출
result = np.where(cond, ar, br)
print(result)

[100 200 301 401]


# 배열 sorting

In [24]:
ar = np.array([300,210,130,400, 500, 50])
result = np.sort(ar)
print("sort를 한 결과:",result)

br = ar.reshape(2,3)
print("br", br)
br.sort(axis=0) #R과 방향이 반대니까 혼동하지 말기!
print(br)

sort를 한 결과: [ 50 130 210 300 400 500]
br [[300 210 130]
 [400 500  50]]
[[300 210  50]
 [400 500 130]]
