# 동일한 차원의 동일한 크기 배열 연산

In [14]:
# 각 요소를 연산하여 동일한 크기의 배열로 리턴
import numpy as np

ar = np.arange(1,6)
br = np.linspace(100, 105, num=5, endpoint=False)

print("ar:",ar)
print("br:",br)

result = ar+br
print("ar+br:", ar+br) #101.은 실수 101.0을 의미 
#정수 + 실수 => 실수로 형변환 된 것 확인가능

#논리 연산
print(ar>br) #bool자료로 변환
result=np.logical_xor(ar,br)
print(result)

ar: [1 2 3 4 5]
br: [100. 101. 102. 103. 104.]
ar+br: [101. 103. 105. 107. 109.]
[False False False False False]
[False False False False False]


# 차원이 다른 배열의 연산 - Broadcast

In [21]:
ar = np.array([100, 200, 300])

#배열의 각 요소에서 100을 뺀 후 배열로 리턴
result = ar-100 #배열 - scalar
print(result)

br = np.arange(1,7)
br = br.reshape(2,3)
print(br)

print("ar+br",ar+br) #행의 수가 달라도 열의 크기만 같다면 연산이 행단위로 진행된다.



[  0 100 200]
[[1 2 3]
 [4 5 6]]
ar+br [[101 202 303]
 [104 205 306]]


# boolean 색인

In [29]:
ar = np.array([100, 200, 301, 215, 294])
print(ar%2 ==0)
print(ar[ar%2 ==0])
# 인덱스 자리에 boolean 결과 값이 나오는 조건을 넣으면 True인 값만 뽑아 낼 수 있다!

[ True  True False False  True]
[100 200 294]


# 난수 Random

In [40]:
#1. 배열 만들기
ar = np.arange(0,48)

#1-1. 기존에 있는 배열을 랜덤하게 배치하기
np.random.shuffle(ar)
print(ar)

#2. 랜덤한 다섯개 숫자를 추출
print(np.random.normal(size=5))

#3. seed를 고정해서 추출할 때 마다 동일한 방법을 만들기
np.random.seed(seed=100) #2의 결과를 고정시켜 버림



[ 6 28 32 26 41 47  5 40 18 31  0 11 36 17 43 35 33  7 45 20 25 19 21 13
  1  4 12 38 22 29  9 27 16 42 46 37 14 44  2 34 30 10 15 23 39  3 24  8]
[-0.40803994 -0.10392514  1.56717879  0.49702472  1.15587233]
