# 배열의 결합

In [8]:
import numpy as np

#1. 일련 번호 형태로 배열 만들기
ar = np.arange(1,13)

#2. 3행 4열로 바꾸어보기
ar = ar.reshape(3,4)

#일정한 간격을 가지고 만들기
br = np.linspace(101,112, num=12)
br = br.reshape(3,4)

#3. 행방향으로 합치기
print("horizontal stack")
print(np.hstack([ar,br]))

#4. 열 방향으로 합치기
print("vertical stack")
print(np.vstack([ar,br]))

horizontal stack
[[  1.   2.   3.   4. 101. 102. 103. 104.]
 [  5.   6.   7.   8. 105. 106. 107. 108.]
 [  9.  10.  11.  12. 109. 110. 111. 112.]]
vertical stack
[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [101. 102. 103. 104.]
 [105. 106. 107. 108.]
 [109. 110. 111. 112.]]
