### 불균형한 클래스의 데이터를 가지고 분석 - 랜덤포레스트 이용

In [19]:
import numpy as np
import pandas as pd

#1. 0이 10개고 1이 90개인 ndarray를 만들어보자
list1 = []
for i in range(0,10,1):
    list1.append(0)

list2 = []
for i in range(0,90,1):
    list2.append(1)


#2. 2개의 list를 가지고 하나의 array 생성
target = np.array(list1+list2) #주의! python에서 list1+list2는 리스트의 결합이지 브로드캐스트 연산이 아니다.

#3. 분류 알고리즘에 위의 데이터를 이용하는 경우?
#현재 0은 10% 1은 90%인 상태

#4. 랜덤 포레스트 사용하기
from sklearn.ensemble import RandomForestClassifier

#4-1. 데이터의 비율이 현저하게 다르니까 가중치를 설정
weights = {0:.9, 1:.1} #기존 비율과 반대로 써주면 됨 ==> 0은 90% . 1은 10%

#랜덤포레스트 매개변수 참고
"""RandomForestClassifier(bootstrap=True, class_weight='balanced',
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators='warn', n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)"""

rfc = RandomForestClassifier(class_weight=weights)
rfc

rfc = RandomForestClassifier(class_weight='balanced') #==> weight를 직접 주지 않고 분류기가 판단하도록 하는 것
rfc

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)
1
90


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

### 샘플링 비율 조정

In [20]:
#cf..샘플링 비율 조정 (이런 방법도 가능하다)
class0 = np.where(target==0)[0] #np에서 특정한 조건에 맞는 데이터를 리턴 받을 때 쓰는 함수. 
#(행번호행렬, 자료형)으로 결과를 리턴
#[0]이 있으면 행번호행렬만 리스트로 리턴됨. 빼면 array 리턴.
class1 = np.where(target==1)[0]
print(class0)
print(len(class0))
print(len(class1))

#cf2... 타겟이 1인 데이터에서 타겟이 0인 데이터만큼 다운 샘플링해서 새로운 데이터 셋을 생성
downsample = np.random.choice(class1, size=len(class0), replace=False)
#cf2-1. class1에서 class0의 데이터 개수만큼 비복원 추출을하자.
result = np.hstack((target[class0],target[downsample]))
result

[0 1 2 3 4 5 6 7 8 9]
10
90


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])